Repository team-gogo/GOGO-Frontend, pull requests merged in 2025-04, with the labels that each got.

#92 토큰 재발급 이슈 해결
  src/app/api/server/[...path]/route.ts
  src/shared/utils/refreshAccessToken.ts
Labels: 1️⃣ Priority: High, 🐞 Bug

#97 회원가입 후 토큰 저장 이슈 해결
  src/app/api/signup/route.ts
Labels: 🐞 Bug

#103 관리자 초대 모달 학생 아이디 누락 이슈 해결
  src/shared/ui/InviteStudentInput/index.tsx
  src/views/stage/create/model/useStageForm.ts
Labels: 🐞 Bug

#101 토큰 재발급 동시성 이슈 해결
  src/app/api/server/[...path]/route.ts
Labels: 🐞 Bug

#105 간단한 텍스트 변경
  src/views/mini-game/model/gameData.tsx
  src/widgets/faq/ui/FaqContainer/index.tsx
  src/widgets/stage/create/constants/miniGames.ts
Labels: 🎨 Type: Publishing

#107 신청 팀 조회 기능 제작
  src/app/(header)/stage/[stageId]/teams/registered/[gameId]/page.tsx
  src/entities/stage/teams/registered/index.ts
  src/entities/stage/teams/registered/ui/RegisterHeader/index.tsx
  src/entities/stage/teams/registered/ui/RegisterItem/index.tsx
  src/shared/types/stage/teams/registered/index.ts
  src/shared/ui/teamDetailModal/index.tsx
  src/views/stage/teams/registered/index.ts
  src/views/stage/teams/registered/ui/StageTeamsRegisteredPage/index.tsx
  src/widgets/stage/apply/ui/StageApply/index.tsx
  src/widgets/stage/teams/registered/api/getTeamRegister.ts
  src/widgets/stage/teams/registered/model/useGetTeamRegisterQuery.ts
  src/widgets/stage/teams/registered/ui/RegisterContainer/index.tsx
Labels: ✨ Feature

#116 변경 사항을 최신 브랜치에 반영합니다
  src/entities/main/model/usePostBettingMatch.ts
  src/entities/main/ui/BettingModal/index.tsx
  src/entities/match/detail/ui/DetailFormation/index.tsx
  src/entities/stage/create/constants/sportTypes.ts
  src/shared/model/sportTypes.tsx
  src/shared/schema/StageDataSchema.ts
  src/shared/schema/createOfficialStageSchema.ts
  src/shared/stores/useBettingMatchArrStore.ts
  src/shared/types/community/create/index.ts
  src/shared/types/community/detail/index.ts
  src/shared/types/community/index.ts
  src/shared/types/main/index.ts
  src/shared/types/my/bet/index.ts
  src/shared/types/stage/apply/index.ts
  src/shared/types/stage/create/index.ts
  src/shared/ui/match/index.tsx
  src/shared/ui/stage/index.tsx
  src/views/main/ui/Mock/getStageInMatch.ts
  src/views/stage/apply/ui/Mock/getMatchListInfo.ts
  src/widgets/match/detail/ui/MatchDetailContainer/index.tsx
  src/widgets/match/detail/ui/MatchTeamFormation/index.tsx
  src/widgets/stage/apply/ui/MatchFilterHeader/index.tsx
  src/widgets/stage/time/hooks/useMatchData.ts
  src/widgets/stage/time/ui/SetTimeContainer/index.tsx
Labels: 🌏 Deploy

#123 랭킹 페이지 디자인 업데이트
  src/entities/ranking/ui/RankingUserItem/index.tsx
  src/entities/ranking/ui/TopRankListItem/index.tsx
  src/shared/model/useNavigation.ts
  src/shared/stores/index.ts
  src/shared/stores/useUserNameStore.ts
  src/shared/stores/useUserStore.ts
  src/shared/ui/header/index.tsx
  src/widgets/faq/model/faqData.ts
  src/widgets/faq/ui/FaqContainer/index.tsx
Labels: 🎨 Type: Publishing

#125 변경 사항을 메인 브랜치에 반영합니다
  public/404Logo.png
  src/app/(header)/main/[stageId]/page.tsx
  src/app/not-found.tsx
  src/entities/main/ui/BatchModal/index.tsx
  src/entities/ranking/ui/RankingUserItem/index.tsx
  src/entities/ranking/ui/TopRankListItem/index.tsx
  src/entities/stage/time/ui/LeagueMatchView/index.tsx
  src/entities/stage/time/ui/MatchSection/index.tsx
  src/entities/stage/time/ui/SingleMatchView/index.tsx
  src/entities/stage/time/ui/TournamentMatchView/index.tsx
  src/entities/stage/ui/model/usePostPassCode.ts
  src/entities/team/api/postTeam.ts
  src/shared/model/useNavigation.ts
  src/shared/stores/index.ts
  src/shared/stores/useUserNameStore.ts
  src/shared/stores/useUserStore.ts
  src/shared/ui/header/index.tsx
  src/shared/ui/stage/index.tsx
  src/views/community/ui/CommunityPage/index.tsx
  src/views/main/ui/MainPage/index.tsx
  src/views/stage/apply/ui/MatchApplyPage/index.tsx
  src/views/stage/time/ui/SetTimePage/index.tsx
  src/widgets/faq/model/faqData.ts
  src/widgets/faq/ui/FaqContainer/index.tsx
  src/widgets/my/bet/ui/PointContainer/index.tsx
  src/widgets/stage/apply/ui/ConfirmStage/index.tsx
  src/widgets/stage/apply/ui/MatchFilterHeader/index.tsx
  src/widgets/stage/bracket/ui/Bracket/index.tsx
  src/widgets/stage/time/ui/SetTimeContainer/index.tsx
  src/widgets/team/ui/ConfirmTeamContainer/index.tsx
  src/widgets/team/ui/PlaceTeamContainer/index.tsx
Labels: 🌏 Deploy

#129 간단한 디자인 변경 사항 적용
  src/widgets/signin/ui/SigninContainer.tsx
  src/widgets/team/ui/CreateTeamContainer/index.tsx
Labels: 🎨 Type: Publishing

#130 변경 사항을 메인 브랜치에 반영합니다
  src/widgets/signin/ui/SigninContainer.tsx
  src/widgets/team/ui/CreateTeamContainer/index.tsx
Labels: 🌏 Deploy

#131 코인 토스 페이지 제작
  public/BackCoin.mp4
  public/FrontCoin.mp4
  src/app/mini-game/[stageId]/coin-toss/page.tsx
  src/entities/mini-game/coin-toss/index.ts
  src/entities/mini-game/coin-toss/ui/CoinTossAnimation/index.tsx
  src/entities/mini-game/coin-toss/ui/CoinTossButton/index.tsx
  src/entities/mini-game/index.ts
  src/entities/mini-game/ui/AnimationDisplayContainer/index.tsx
  src/entities/mini-game/ui/BettingActionBox/index.tsx
  src/entities/mini-game/ui/GameSelectionCard/index.tsx
  src/entities/mini-game/ui/PlayerResources/index.tsx
  src/middleware.ts
  src/shared/types/mini-game/coin-toss/index.ts
  src/shared/ui/systemLabel/index.tsx
  src/views/mini-game/coin-toss/api/postCoinToss.ts
  src/views/mini-game/coin-toss/index.ts
  src/views/mini-game/coin-toss/model/usePostCoinToss.ts
  src/views/mini-game/coin-toss/ui/CoinTossPage/index.tsx
  src/widgets/main/ui/MiniGameSection/index.tsx
  src/widgets/mini-game/index.ts
  src/widgets/mini-game/ui/ControlForm/index.tsx
Labels: 🎨 Type: Publishing

#165 야바위 게임 제작
  package-lock.json
  package.json
  public/ball.png
  public/cup.png
  src/app/mini-game/[stageId]/yavarwee/page.tsx
  src/entities/mini-game/ui/BettingActionBox/index.tsx
  src/entities/mini-game/ui/PlayerResources/index.tsx
  src/entities/mini-game/yavarwee/index.ts
  src/entities/mini-game/yavarwee/ui/Round/index.tsx
  src/entities/mini-game/yavarwee/ui/YavarweeAnimation/index.tsx
  src/entities/mini-game/yavarwee/ui/YavarweeButton/index.tsx
  src/shared/types/mini-game/yavarwee/index.ts
  src/views/mini-game/coin-toss/ui/CoinTossPage/index.tsx
  src/views/mini-game/yavarwee/api/postBetyavarwee.ts
  src/views/mini-game/yavarwee/api/postComfirmYavarwee.ts
  src/views/mini-game/yavarwee/index.ts
  src/views/mini-game/yavarwee/model/encrypt.ts
  src/views/mini-game/yavarwee/model/useBetYavarweeMutation.ts
  src/views/mini-game/yavarwee/model/useComfirmYavarweeMutation.ts
  src/views/mini-game/yavarwee/ui/YavarweePage/index.tsx
  src/widgets/main/ui/MiniGameSection/index.tsx
  src/widgets/mini-game/ui/ControlForm/index.tsx
  src/widgets/mini-game/yavarwee/index.ts
  src/widgets/mini-game/yavarwee/ui/RoundContainer/index.tsx
Labels: ✨ Feature, 📬 Type: API, 🎨 Type: Publishing

#166 야바위 코인토스 최소 최대 배팅 포인트 설정
  src/entities/mini-game/ui/BettingActionBox/index.tsx
  src/middleware.ts
  src/shared/assets/svg/LineStroke.tsx
  src/shared/assets/svg/WarningIcon.tsx
  src/shared/types/mini-game/index.ts
  src/views/mini-game/api/getBetLimit.ts
  src/views/mini-game/coin-toss/ui/CoinTossPage/index.tsx
  src/views/mini-game/model/useGetBetLimit.ts
  src/views/mini-game/yavarwee/ui/YavarweePage/index.tsx
  src/widgets/mini-game/ui/ControlForm/index.tsx
Labels: 🎨 Type: Publishing

#169 야바위 컵 선택 3초 제한 기능 제작
  src/entities/mini-game/yavarwee/ui/YavarweeAnimation/index.tsx
  src/entities/mini-game/yavarwee/ui/YavarweeButton/index.tsx
  src/views/mini-game/yavarwee/ui/YavarweePage/index.tsx
Labels: ✨ Feature

#171 야바위 타이머 컴포넌트 언마운트시 타이머 불일치 이슈 해결
  src/entities/mini-game/yavarwee/ui/YavarweeAnimation/index.tsx
Labels: 🐞 Bug

#173 커뮤니티 페이지 개선
  src/entities/community/detail/model/usePostBoardCommentMutation.ts
  src/entities/community/detail/model/usePostBoardLikeMutation.ts
  src/entities/community/detail/ui/CommentInput/index.tsx
  src/entities/community/detail/ui/CommentItem/index.tsx
  src/entities/community/detail/ui/CommunityContent/index.tsx
  src/entities/community/ui/CommunityItem/index.tsx
  src/views/community/detail/ui/CommunityDetailPage/index.tsx
  src/widgets/community/ui/CommunityItemContainer/index.tsx
Labels: ⚡️performance, ♻️ Refactor, ⚡️ Simple

#176 faq 항목 변경
  src/entities/faq/ui/FaqItem/index.tsx
  src/entities/faq/ui/FaqSearch/index.tsx
  src/shared/assets/icons/QuestionIcon.tsx
  src/shared/assets/icons/SearchIcon.tsx
  src/widgets/faq/model/faqData.ts
  src/widgets/faq/ui/FaqContainer/index.tsx
Labels: 🎨 Type: Publishing

#177 메인 브랜치에 반영합니다
  src/entities/faq/ui/FaqItem/index.tsx
  src/entities/faq/ui/FaqSearch/index.tsx
  src/shared/assets/icons/QuestionIcon.tsx
  src/shared/assets/icons/SearchIcon.tsx
  src/widgets/faq/model/faqData.ts
  src/widgets/faq/ui/FaqContainer/index.tsx
Labels: 🌏 Deploy

#178 코인토스 영상 화질 상승
  public/BackCoin.mp4
  public/FrontCoin.mp4
Labels: ⚡️ Simple

#179 배포 환경에 반영합니다
  public/BackCoin.mp4
  public/FrontCoin.mp4
Labels: 🌏 Deploy

#193 faq 항목 추가
  src/widgets/faq/model/faqData.ts
Labels: 🎨 Type: Publishing

#203 최신 브랜치 반영
  src/entities/community/detail/ui/SortDropdown/index.tsx
  src/shared/assets/icons/HeartIcon.tsx
  src/shared/model/sportTypes.tsx
  src/views/community/detail/ui/CommunityDetailPage/index.tsx
  src/widgets/community/detail/ui/CommentContainer/index.tsx
Labels: 🌏 Deploy

#210 댓글 정렬 드롭다운 디자인 반영
  src/entities/community/detail/ui/SortDropdown/index.tsx
Labels: 3️⃣ Priority: Low, 🎨 Type: Publishing

#211 커뮤니티 이미지 첨부/조회 기능 구현
  next.config.mjs
  src/entities/community/detail/ui/CommunityContent/index.tsx
  src/shared/assets/svg/TrashIcon.tsx
  src/shared/types/community/create/index.ts
  src/shared/types/community/detail/index.ts
  src/shared/ui/input/index.tsx
  src/views/community/detail/ui/CommunityDetailPage/index.tsx
  src/widgets/community/create/api/postCommunity.ts
  src/widgets/community/create/api/postImage.ts
  src/widgets/community/create/ui/CommunityCreateContainer/index.tsx
Labels: 1️⃣ Priority: High, ✨ Feature

#215 6팀일 때 승리팀 처리
  src/shared/ui/BracketTeamDisplay/index.tsx
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#214 StageApply 컴포넌트 마운트 시 game 개수 만큼 요청을 보내는 문제 해결
  src/views/stage/apply/ui/MatchApplyPage/index.tsx
  src/widgets/stage/apply/ui/StageApply/index.tsx
Labels: ⚡️performance, ⚡️ Simple

#222 변경 사항을 배포 브랜치에 반영
  src/app/(header)/coupon/page.tsx
  src/entities/community/detail/ui/CommunityContent/index.tsx
  src/entities/community/ui/CommunityItem/index.tsx
  src/entities/main/ui/DateContainer/index.tsx
  src/entities/match/detail/ui/DetailFormation/index.tsx
  src/shared/assets/icons/ViewsIcon.tsx
  src/shared/assets/icons/index.ts
  src/shared/assets/svg/NormalIcon.tsx
  src/shared/assets/svg/PointCircleIcon.tsx
  src/shared/assets/svg/RandomIcon.tsx
  src/shared/assets/svg/index.ts
  src/shared/types/community/detail/index.ts
  src/shared/types/community/index.ts
  src/shared/types/coupon/index.ts
  src/shared/ui/match/index.tsx
  src/shared/ui/stageMatchContainer/index.tsx
  src/views/community/detail/ui/CommunityDetailPage/index.tsx
  src/views/community/index.ts
  src/views/community/ui/Mock/getBoardMock.ts
  src/views/coupon/api/getMyCouponInfo.ts
  src/views/coupon/api/postMyCoupon.ts
  src/views/coupon/index.ts
  src/views/coupon/model/useGetMyCouponInfo.ts
  src/views/coupon/model/usePostMyCoupon.ts
  src/views/coupon/ui/CouponPage/index.tsx
  src/views/coupon/ui/index.ts
  src/views/main/index.ts
  src/views/main/ui/MainPage/index.tsx
  src/views/main/ui/Mock/getBoardMock.ts
  src/views/stage/apply/ui/MatchApplyPage/index.tsx
  src/views/stage/ui/StagePage/index.tsx
  src/widgets/match/ui/MatchNameContainer/index.tsx
  src/widgets/stage/apply/ui/StageApply/index.tsx
Labels: 🌏 Deploy
