Repository team-gogo/GOGO-Frontend, pull requests merged in 2025-03, with the labels that each got.

#9 변경된 suit 폰트 적용
  src/app/layout.tsx
  src/app/page.tsx
  src/shared/styles/fonts.ts
  src/shared/styles/fonts/GmarketSansTTFBold.ttf
  src/shared/styles/fonts/GmarketSansTTFLight.ttf
  src/shared/styles/fonts/GmarketSansTTFMedium.ttf
  src/shared/styles/fonts/SUIT-Bold.woff2
  src/shared/styles/fonts/SUIT-ExtraBold.woff2
  src/shared/styles/fonts/SUIT-ExtraLight.woff2
  src/shared/styles/fonts/SUIT-Heavy.woff2
  src/shared/styles/fonts/SUIT-Light.woff2
  src/shared/styles/fonts/SUIT-Medium.woff2
  src/shared/styles/fonts/SUIT-Regular.woff2
  src/shared/styles/fonts/SUIT-SemiBold.woff2
  src/shared/styles/fonts/SUIT-Thin.woff2
  src/shared/styles/globals.css
  tailwind.config.ts
Labels: ⚡️ Simple, 🎨 Type: Publishing

#7 공용 컴포넌트 input, button 제작
  package-lock.json
  package.json
  src/shared/ui/button/index.tsx
  src/shared/ui/input/index.tsx
  src/shared/utils/cn.ts
Labels: 🎨 Type: Publishing

#5 로그인 페이지 제작
  .github/ISSUE_TEMPLATE/bug.yml
  src/app/signin/page.tsx
  src/entities/index.tsx
  src/entities/signin/index.ts
  src/entities/signin/ui/GoogleButton.tsx
  src/shared/assets/svg/GoogleLogo.tsx
  src/shared/assets/svg/Logo.tsx
  src/shared/assets/svg/index.ts
  src/views/index.tsx
  src/views/signin/index.ts
  src/views/signin/ui/SigninPage/index.tsx
  src/widgets/index.tsx
  src/widgets/signin/index.ts
  src/widgets/signin/ui/SigninContainer.tsx
Labels: 🎨 Type: Publishing

#12 회원가입 페이지 제작
  .gitignore
  package-lock.json
  package.json
  src/app/signup/page.tsx
  src/entities/signup/api/getSchool.ts
  src/entities/signup/model/getGenderButtonStyles.ts
  src/entities/signup/model/useSchoolQuery.ts
  src/entities/signup/ui/GenderButton/index.tsx
  src/entities/signup/ui/GenderSelection/index.tsx
  src/entities/signup/ui/PersonalInfoInputs/index.tsx
  src/entities/signup/ui/SchoolInput.tsx/index.tsx
  src/entities/signup/ui/SchoolSearchResults/index.tsx
  src/shared/assets/icons/SearchIcon.tsx
  src/shared/assets/icons/index.ts
  src/shared/types/signup/index.ts
  src/shared/ui/button/index.tsx
  src/shared/ui/input/index.tsx
  src/views/ signup/index.ts
  src/views/ signup/ui/SignupPage/index.tsx
  src/widgets/signin/ui/SigninContainer.tsx
  src/widgets/signup/index.ts
  src/widgets/signup/model/formatSignupData.ts
  src/widgets/signup/model/useSignupForm.ts
  src/widgets/signup/ui/SignupContainer.tsx
Labels: ✨ Feature, 🎨 Type: Publishing

#13 header 제작
  src/shared/assets/svg/FaqIcon.tsx
  src/shared/assets/svg/HelpIcon.tsx
  src/shared/assets/svg/MiniGameIcon.tsx
  src/shared/assets/svg/MyIcon.tsx
  src/shared/assets/svg/NoticeIcon.tsx
  src/shared/assets/svg/StageIcon.tsx
  src/shared/assets/svg/index.ts
  src/shared/ui/header/index.tsx
Labels: 🎨 Type: Publishing

#15 header 스타일 개선
  .prettierrc
  src/app/page.tsx
  src/shared/assets/svg/Logo.tsx
  src/shared/model/navLinks.ts
  src/shared/model/useNavigation.ts
  src/shared/ui/header/index.tsx
  tailwind.config.ts
Labels: 🎨 Type: Publishing

#14 faq 페이지 제작
  src/app/faq/page.tsx
  src/app/signin/page.tsx
  src/app/signup/page.tsx
  src/entities/faq/index.ts
  src/entities/faq/ui/FaqItem/index.tsx
  src/entities/faq/ui/FaqSearch/index.tsx
  src/entities/signin/ui/GoogleButton.tsx
  src/entities/signup/ui/GenderButton/index.tsx
  src/entities/signup/ui/GenderSelection/index.tsx
  src/entities/signup/ui/PersonalInfoInputs/index.tsx
  src/entities/signup/ui/SchoolInput.tsx/index.tsx
  src/entities/signup/ui/SchoolSearchResults/index.tsx
  src/shared/assets/icons/ArrowDownIcon.tsx
  src/shared/assets/icons/ArrowUpIcon.tsx
  src/shared/assets/icons/BlueQuestionIcon.tsx
  src/shared/assets/icons/QuestionIcon.tsx
  src/shared/assets/icons/SearchIcon.tsx
  src/shared/assets/icons/index.ts
  src/shared/assets/svg/GoogleLogo.tsx
  src/shared/assets/svg/Logo.tsx
  src/views/ signup/ui/SignupPage/index.tsx
  src/views/faq/index.ts
  src/views/faq/ui/FaqPage/index.tsx
  src/views/signin/ui/SigninPage/index.tsx
  src/widgets/faq/index.ts
  src/widgets/faq/model/faqData.ts
  src/widgets/faq/ui/FaqContainer/index.tsx
  src/widgets/signin/ui/SigninContainer.tsx
  src/widgets/signup/ui/SignupContainer.tsx
Labels: 🎨 Type: Publishing

#17 header group route로 적용
  src/app/(header)/faq/page.tsx
  src/app/(header)/layout.tsx
  src/app/(header)/page.tsx
  src/app/layout.tsx
  src/views/ signup/ui/SignupPage/index.tsx
  src/views/faq/ui/FaqPage/index.tsx
  src/views/signin/ui/SigninPage/index.tsx
  src/widgets/faq/ui/FaqContainer/index.tsx
  src/widgets/signin/ui/SigninContainer.tsx
  src/widgets/signup/ui/SignupContainer.tsx
Labels: ✨ Feature, ⚡️ Simple

#23 변경된 회원가입 디자인 반영
  src/entities/signup/ui/PersonalInfoInputs/index.tsx
  src/entities/signup/ui/SchoolInput.tsx/index.tsx
  src/entities/signup/ui/SchoolSearchResults/index.tsx
  src/shared/model/preventInvalidInputNumber.ts
  src/widgets/signup/ui/SignupContainer.tsx
Labels: 🎨 Type: Publishing

#22 미니 게임 페이지 제작
  src/app/(header)/mini-game/page.tsx
  src/app/(header)/page.tsx
  src/entities/mini-game/index.ts
  src/entities/mini-game/ui/GameInfo/index.tsx
  src/entities/mini-game/ui/GameSelectionCard/index.tsx
  src/entities/mini-game/ui/StoreInfo/index.tsx
  src/entities/mini-game/ui/Title/index.tsx
  src/shared/assets/icons/CircleQuestionIcon.tsx
  src/shared/assets/icons/CoinIcon.tsx
  src/shared/assets/icons/PlinkoIcon.tsx
  src/shared/assets/icons/PointIcon.tsx
  src/shared/assets/icons/ShellGameIcon.tsx
  src/shared/assets/icons/StoreIcon.tsx
  src/shared/assets/icons/TicketIcon.tsx
  src/shared/assets/icons/index.ts
  src/views/mini-game/index.ts
  src/views/mini-game/model/gameData.tsx
  src/views/mini-game/model/storeData.tsx
  src/views/mini-game/ui/MiniGamePage/index.tsx
  src/widgets/mini-game/index.ts
  src/widgets/mini-game/ui/GameCardContainer/index.tsx
  src/widgets/mini-game/ui/InfoContainer/index.tsx
Labels: 🎨 Type: Publishing

#25 커뮤니티 조회 페이지 제작
  src/app/(header)/community/page.tsx
  src/entities/community/index.ts
  src/entities/community/ui/CommunityHeader/index.tsx
  src/entities/community/ui/CommunityItem/index.tsx
  src/entities/community/ui/FilterButton/index.tsx
  src/entities/community/ui/Modal/index.tsx
  src/entities/community/ui/WriteButton/index.tsx
  src/shared/assets/icons/ArrowDownIcon.tsx
  src/shared/assets/icons/ArrowUpIcon.tsx
  src/shared/assets/icons/CommentIcon.tsx
  src/shared/assets/icons/HeartIcon.tsx
  src/shared/assets/icons/index.ts
  src/shared/assets/svg/BadmintonIcon.tsx
  src/shared/assets/svg/BaseballIcon.tsx
  src/shared/assets/svg/BasketballIcon.tsx
  src/shared/assets/svg/CirclePlusIcon.tsx
  src/shared/assets/svg/CommunityIcon.tsx
  src/shared/assets/svg/EtcIcon.tsx
  src/shared/assets/svg/FilterIcon.tsx
  src/shared/assets/svg/LoLIcon.tsx
  src/shared/assets/svg/SoccerIcon.tsx
  src/shared/assets/svg/VolleyballIcon.tsx
  src/shared/assets/svg/WarningIcon.tsx
  src/shared/assets/svg/XIcon.tsx
  src/shared/assets/svg/index.ts
  src/shared/model/sportTypes.tsx
  src/shared/types/community/index.ts
  src/shared/ui/modalLayout/index.tsx
  src/shared/ui/sportTypelabel/index.tsx
  src/shared/utils/cn.ts
  src/views/community/index.ts
  src/views/community/ui/CommunityPage/index.tsx
  src/views/faq/ui/FaqPage/index.tsx
  src/widgets/community/Mock/getBoardMock.ts
  src/widgets/community/index.ts
  src/widgets/community/ui/CommunityItemContainer/index.tsx
  src/widgets/community/ui/CommunityToolbar/index.tsx
Labels: 🎨 Type: Publishing

#33 fix: 폴더 tab 문제 해결
  src/app/signup/page.tsx
  src/views/signup/index.ts
  src/views/signup/ui/SignupPage/index.tsx
Labels: ⚡️ Simple

#36 ci의 맨션 유저를 변경
  .github/workflows/GOGO_CI.yml
  src/app/community/detail/[id]/page.tsx
  src/entities/community/detail/index.ts
  src/entities/community/detail/ui/CommentInput/index.tsx
  src/entities/community/detail/ui/CommentItem/index.tsx
  src/entities/community/detail/ui/CommunityContent/index.tsx
  src/entities/community/ui/CommunityItem/index.tsx
  src/shared/assets/svg/LeftArrow.tsx
  src/shared/assets/svg/PersonIcon.tsx
  src/shared/assets/svg/SelectHeartIcon.tsx
  src/shared/assets/svg/SendIcon.tsx
  src/shared/assets/svg/index.ts
  src/shared/model/formatIsoDate.ts
  src/shared/types/community/detail/index.ts
  src/shared/ui/backPageButton/index.tsx
  src/shared/ui/input/index.tsx
  src/views/community/detail/Mock/getCommunityDetail.ts
  src/views/community/detail/index.ts
  src/views/community/detail/ui/CommunityDetailPage/index.tsx
  src/widgets/community/detail/index.ts
  src/widgets/community/detail/ui/CommentContainer/index.tsx
Labels: 📝 Docs

#43 랭킹 페이지 제작
  src/app/(header)/ranking/page.tsx
  src/entities/ranking/index.ts
  src/entities/ranking/ui/RankingUserItem/index.tsx
  src/entities/ranking/ui/TopRankListItem/index.tsx
  src/shared/assets/svg/Medal.tsx
  src/shared/assets/svg/PointIcon.tsx
  src/shared/assets/svg/index.ts
  src/shared/types/ranking/index.ts
  src/views/ranking/Mock/getRankingMock.ts
  src/views/ranking/index.ts
  src/views/ranking/ui/RankingPage/index.tsx
  src/widgets/ranking/index.ts
  src/widgets/ranking/ui/RankingUserContainer/index.tsx
  src/widgets/ranking/ui/TopRankListContainer/index.tsx
Labels: 🎨 Type: Publishing

#52 공식 경기 생성 기능 제작
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/stage/create/official/page.tsx
  src/entities/mini-game/ui/StoreInfo/index.tsx
  src/entities/stage/create/official/constants/sportTypes.ts
  src/entities/stage/create/official/index.ts
  src/entities/stage/create/official/ui/AddButton/index.tsx
  src/entities/stage/create/official/ui/AddGameButton/index.tsx
  src/entities/stage/create/official/ui/GameField/index.tsx
  src/entities/stage/create/official/ui/GameInputBox/index.tsx
  src/entities/stage/create/official/ui/SelectStageType/index.tsx
  src/shared/assets/icons/PointIcon.tsx
  src/shared/assets/icons/index.ts
  src/shared/assets/svg/CircleEliminate.tsx
  src/shared/assets/svg/PersonIcon.tsx
  src/shared/assets/svg/index.ts
  src/shared/libs/ToastProvider.tsx
  src/shared/model/formErrorUtils.ts
  src/shared/types/createStage/index.ts
  src/shared/types/stage/create/official/index.ts
  src/shared/ui/SelectOption/index.tsx
  src/shared/ui/backPageButton/index.tsx
  src/shared/ui/input/index.tsx
  src/views/stage/create/official/index.ts
  src/views/stage/create/official/model/useOfficialStageForm.ts
  src/views/stage/create/official/ui/OfficialCreatePage/index.tsx
  src/widgets/stage/create/official/constants/matchTypes.ts
  src/widgets/stage/create/official/constants/miniGames.ts
  src/widgets/stage/create/official/constants/storeItems.ts
  src/widgets/stage/create/official/index.ts
  src/widgets/stage/create/official/model/miniGameUtils.ts
  src/widgets/stage/create/official/model/storeUtils.ts
  src/widgets/stage/create/official/model/useMatchSetting.ts
  src/widgets/stage/create/official/model/validateFields.ts
  src/widgets/stage/create/official/ui/EntryNumberInput/index.tsx
  src/widgets/stage/create/official/ui/InviteStudentInput/index.tsx
  src/widgets/stage/create/official/ui/MatchSettingContainer/index.tsx
  src/widgets/stage/create/official/ui/MiniGameContainer/index.tsx
  src/widgets/stage/create/official/ui/OfficialCreateContainer.tsx
  src/widgets/stage/create/official/ui/RuleInputContainer/index.tsx
  src/widgets/stage/create/official/ui/StageInputContainer/index.tsx
  src/widgets/stage/create/official/ui/StoreContainer/index.tsx
Labels: ✨ Feature, ♻️ Refactor

#60 로그인 api 연결 진행
  src/app/api/auth/callback/route.ts
  src/middleware.ts
  src/shared/api/http.ts
  src/shared/api/instance.ts
  src/shared/types/signin/index.ts
  src/views/signin/ui/SigninPage/index.tsx
Labels: 📬 Type: API

#61 회원가입 기능 제작
  src/app/api/user/auth/signin/route.ts
  src/app/api/user/auth/signup/route.ts
  src/middleware.ts
  src/shared/api/instance.ts
  src/shared/types/signup/index.ts
  src/widgets/signup/api/postSignup.ts
  src/widgets/signup/model/formatSignupData.ts
  src/widgets/signup/model/useSignup.ts
  src/widgets/signup/model/useSignupForm.ts
  src/widgets/signup/ui/SignupContainer.tsx
Labels: 📬 Type: API

#63 라우트 핸들러 제작
  src/app/api/server/[...path]/route.ts
  src/app/api/signin/route.ts
  src/app/api/stage/fast/route.ts
  src/app/api/stage/official/route.ts
  src/app/api/user/auth/signup/route.ts
  src/app/api/user/student/search/route.ts
  src/middleware.ts
  src/views/stage/create/api/postFastStage.ts
  src/views/stage/create/api/postOfficialStage.ts
  src/widgets/signup/api/postSignup.ts
  src/widgets/stage/create/api/getSearchStudent.ts
Labels: ✨ Feature, 📬 Type: API

#72 랭킹 페이지 제작
  src/app/(header)/ranking/[stageId]/page.tsx
  src/entities/ranking/ui/TopRankListItem/index.tsx
  src/views/ranking/api/getRank.ts
  src/views/ranking/model/useGetRankingQuery.ts
  src/views/ranking/ui/RankingPage/index.tsx
Labels: 📬 Type: API

#76 회원가입시 토큰 재발급
  src/app/api/signin/route.ts
  src/app/api/signup/route.ts
  src/widgets/signup/api/postSignup.ts
Labels: 📬 Type: API

#74 커뮤니티 페이지 제작
  src/app/(header)/community/[stageId]/page.tsx
  src/app/(header)/community/page.tsx
  src/app/api/server/[...path]/route.ts
  src/app/community/[stageId]/detail/[boardId]/page.tsx
  src/app/community/create/[stageId]/page.tsx
  src/entities/community/api/getStageGame.ts
  src/entities/community/create/ui/CategoryContainer/index.tsx
  src/entities/community/detail/api/postBoardComment.ts
  src/entities/community/detail/api/postBoardLike.ts
  src/entities/community/detail/api/postCommentLike.ts
  src/entities/community/detail/model/usePostBoardCommentMutation.ts
  src/entities/community/detail/model/usePostBoardLikeMutation.ts
  src/entities/community/detail/model/usePostCommentLike.ts
  src/entities/community/detail/ui/CommentInput/index.tsx
  src/entities/community/detail/ui/CommentItem/index.tsx
  src/entities/community/detail/ui/CommunityContent/index.tsx
  src/entities/community/index.ts
  src/entities/community/model/useCategoryTypes.ts
  src/entities/community/model/useGetStageGameQuery.ts
  src/entities/community/ui/CommunityItem/index.tsx
  src/entities/community/ui/NavigationBar/index.tsx
  src/entities/community/ui/WriteButton/index.tsx
  src/shared/model/useSelectSort.ts
  src/shared/types/community/detail/index.ts
  src/shared/types/community/index.ts
  src/shared/ui/CategoryTypeModal/index.tsx
  src/views/community/detail/Mock/getCommunityDetail.ts
  src/views/community/detail/api/getCommunityDetail.ts
  src/views/community/detail/model/useGetCommunityDetailQuery.ts
  src/views/community/detail/ui/CommunityDetailPage/index.tsx
  src/views/community/ui/CommunityPage/index.tsx
  src/views/community/ui/Mock/getBoardMock.ts
  src/views/main/ui/MainPage/index.tsx
  src/views/main/ui/Mock/getBoardMock.ts
  src/widgets/community/api/getCommunityList.ts
  src/widgets/community/create/api/postCommunity.ts
  src/widgets/community/create/model/useCreateCommunityMutation.ts
  src/widgets/community/create/ui/CommunityCreateContainer/index.tsx
  src/widgets/community/detail/ui/CommentContainer/index.tsx
  src/widgets/community/model/useGetCommunityQuery.ts
  src/widgets/community/ui/CommunityItemContainer/index.tsx
  src/widgets/community/ui/CommunityToolbar/index.tsx
  src/widgets/stage/apply/ui/MatchFilterHeader/index.tsx
Labels: 📬 Type: API

#78 미니게임 상점 페이지 제작
  src/app/(header)/mini-game/[stageId]/page.tsx
  src/entities/mini-game/ui/GameInfo/index.tsx
  src/entities/mini-game/ui/GameSelectionCard/index.tsx
  src/entities/mini-game/ui/StoreInfo/index.tsx
  src/entities/stage/ui/model/usePostPassCode.ts
  src/shared/assets/icons/CoinIcon.tsx
  src/shared/assets/icons/PlinkoIcon.tsx
  src/shared/assets/icons/ShellGameIcon.tsx
  src/shared/assets/icons/StoreIcon.tsx
  src/shared/assets/icons/TicketIcon.tsx
  src/shared/assets/svg/MiniGameIcon.tsx
  src/shared/assets/svg/XIcon.tsx
  src/shared/types/mini-game/index.ts
  src/shared/ui/MiniGameDescriptionModal/index.tsx
  src/shared/ui/modalLayout/index.tsx
  src/shared/ui/stage/index.tsx
  src/views/main/ui/MainPage/index.tsx
  src/views/mini-game/api/getActiveGame.ts
  src/views/mini-game/api/getMyPoint.ts
  src/views/mini-game/api/getMyTicket.ts
  src/views/mini-game/api/getShopTicketStatus.ts
  src/views/mini-game/api/postBuyTicket.ts
  src/views/mini-game/model/gameData.tsx
  src/views/mini-game/model/storeData.tsx
  src/views/mini-game/model/useGetActiveGameQuery.ts
  src/views/mini-game/model/useGetMyPointQuery.ts
  src/views/mini-game/model/useGetMyTicketQuery.ts
  src/views/mini-game/model/useGetShopTicketStatusQuery.ts
  src/views/mini-game/model/usePostBuyTicketMutation.ts
  src/views/mini-game/ui/MiniGamePage/index.tsx
  src/widgets/mini-game/ui/GameCardContainer/index.tsx
  src/widgets/mini-game/ui/InfoContainer/index.tsx
Labels: 📬 Type: API

#80 미들웨어 설정 진행
  src/app/api/signin/route.ts
  src/app/api/signup/route.ts
  src/app/callback/page.tsx
  src/middleware.ts
Labels: ✨ Feature, 📬 Type: API

#85 base url 접속시 /stage로 리다이렉트
  src/app/page.tsx
Labels: ⚡️ Simple

#83 토큰 재발급 로직 제작
  src/app/api/server/[...path]/route.ts
  src/app/api/signin/route.ts
  src/app/api/signup/route.ts
  src/entities/community/api/getStageGame.ts
  src/entities/community/detail/api/postBoardComment.ts
  src/entities/community/detail/api/postBoardLike.ts
  src/entities/community/detail/api/postCommentLike.ts
  src/entities/main/api/postBatchMatch.ts
  src/entities/main/api/postBettingMatch.ts
  src/entities/main/api/postCancleBatch.ts
  src/entities/stage/api/getStageMaintainer.ts
  src/entities/stage/ui/api/postPassCode.ts
  src/entities/team/api/getTempTeam.ts
  src/entities/team/api/postTeam.ts
  src/shared/api/clientInstance.ts
  src/shared/api/http.ts
  src/shared/api/serverInstance.ts
  src/shared/model/useDebouncedValue.ts
  src/shared/ui/modalLayout/index.tsx
  src/shared/utils/clearAuthCookies.ts
  src/shared/utils/refreshAccessToken.ts
  src/shared/utils/setAuthCookies.ts
  src/views/community/detail/api/getCommunityDetail.ts
  src/views/main/api/getSearchMatch.ts
  src/views/main/api/getUserStagePoint.ts
  src/views/main/api/patchMatchNotice.ts
  src/views/match/api/getTeamDetail.ts
  src/views/mini-game/api/getActiveGame.ts
  src/views/mini-game/api/getMyPoint.ts
  src/views/mini-game/api/getMyTicket.ts
  src/views/mini-game/api/getShopTicketStatus.ts
  src/views/mini-game/api/postBuyTicket.ts
  src/views/mini-game/api/postPlinkoGame.ts
  src/views/my/api/getMyBettingMatch.ts
  src/views/my/api/getMyInfo.ts
  src/views/my/api/getMyStageInfo.ts
  src/views/my/api/getMyTempPoint.ts
  src/views/my/edit/api/patchMyInfo.ts
  src/views/ranking/api/getRank.ts
  src/views/stage/apply/api/getMatchApplyList.ts
  src/views/stage/create/api/postFastStage.ts
  src/views/stage/create/api/postOfficialStage.ts
  src/views/stage/ui/api/getStageList.ts
  src/widgets/community/api/getCommunityList.ts
  src/widgets/community/create/api/postCommunity.ts
  src/widgets/signup/api/postSignup.ts
  src/widgets/stage/create/api/getSearchStudent.ts
  src/widgets/stage/create/model/useSearchStudentQuery.ts
Labels: ✨ Feature

#90 간단한 변경사항 적용
  src/entities/community/detail/ui/CommentInput/index.tsx
  src/entities/community/detail/ui/CommentItem/index.tsx
  src/entities/faq/ui/FaqSearch/index.tsx
  src/views/mini-game/model/storeData.tsx
  src/views/mini-game/model/useGetActiveGameQuery.ts
  src/views/mini-game/model/useGetMyPointQuery.ts
  src/views/mini-game/model/useGetMyTicketQuery.ts
  src/views/mini-game/model/useGetShopTicketStatusQuery.ts
  src/views/mini-game/model/usePostBuyTicketMutation.ts
  src/views/mini-game/ui/MiniGamePage/index.tsx
  src/widgets/community/create/ui/CommunityCreateContainer/index.tsx
  src/widgets/faq/ui/FaqContainer/index.tsx
  src/widgets/signup/model/useSignupForm.ts
  src/widgets/stage/create/ui/RuleInputContainer/index.tsx
Labels: ⚡️ Simple
